make overwrite of nodeType configurable
nodeType label does not belong to the gpu-operator label namespace
and should not be overwritten. other applications in the cluster
may be using that label for their own logic, and overwriting that
label may interfere with other applications.

by default, disable the overwrite of nodeType.

diff --git a/driver-manager b/driver-manager
--- a/driver-manager
+++ b/driver-manager
@@ -36,6 +36,7 @@ MIG_MANAGER_DEPLOYED=""
 SANDBOX_VALIDATOR_DEPLOYED=""
 SANDBOX_PLUGIN_DEPLOYED=""
 VGPU_DEVICE_MANAGER_DEPLOYED=""
+ENABLE_NODE_TYPE_LABELING=${ENABLE_NODE_TYPE_LABELING:-"false"}
 NODE_TYPE_LABEL=""
 AUTO_UPGRADE_POLICY_ENABLED=""
 
@@ -229,13 +230,15 @@ _fetch_current_labels() {
     fi
     echo "Current value of 'nvidia.com/gpu.deploy.vgpu-device-manager=${VGPU_DEVICE_MANAGER_DEPLOYED}'"
 
-    echo "Getting current value of the 'nodeType' node label(used by NVIDIA Fleet Command)"
-    NODE_TYPE_LABEL=$(kubectl get nodes ${NODE_NAME} -o=jsonpath='{$.metadata.labels.nodeType}')
-    if [ "${?}" != "0" ]; then
-        echo "Unable to get the value of the 'nodeType' label"
-        exit 1
+    if [ "${ENABLE_NODE_TYPE_LABELING}" = "true" ]; then
+        echo "Getting current value of the 'nodeType' node label(used by NVIDIA Fleet Command)"
+        NODE_TYPE_LABEL=$(kubectl get nodes ${NODE_NAME} -o=jsonpath='{$.metadata.labels.nodeType}')
+        if [ "${?}" != "0" ]; then
+            echo "Unable to get the value of the 'nodeType' label"
+            exit 1
+        fi
+        echo "Current value of 'nodeType=${NODE_TYPE_LABEL}'"
     fi
-    echo "Current value of 'nodeType=${NODE_TYPE_LABEL}'"
 
 }
 
@@ -308,14 +311,16 @@ _evict_all_gpu_operator_components() {
         return 1
     fi
 
-    # check for nodeType=gpu label used by NVIDIA Fleet Command
-    if [ "${NODE_TYPE_LABEL}" == "gpu" ]; then
-        echo "Shutting down GPU clients on NVIDIA Fleet Command"
-        kubectl label --overwrite node ${NODE_NAME} \
-            nodeType=$(_maybe_set_paused ${NODE_TYPE_LABEL})
+    if [ "${ENABLE_NODE_TYPE_LABELING}" = "true" ]; then
+        # check for nodeType=gpu label used by NVIDIA Fleet Command
+        if [ "${NODE_TYPE_LABEL}" == "gpu" ]; then
+            echo "Shutting down GPU clients on NVIDIA Fleet Command"
+            kubectl label --overwrite node ${NODE_NAME} \
+                nodeType=$(_maybe_set_paused ${NODE_TYPE_LABEL})
 
-        if [ "$?" != "0" ]; then
-            return 1
+            if [ "$?" != "0" ]; then
+                return 1
+            fi
         fi
     fi
 
@@ -447,13 +452,15 @@ _reschedule_gpu_operator_components() {
         return 1
     fi
 
-    # check for nodeType=gpu label used by NVIDIA Fleet Command
-    if [ "${NODE_TYPE_LABEL}" != "" ]; then
-        echo "Restarting GPU clients on NVIDIA Fleet Command"
-        kubectl label --overwrite node ${NODE_NAME} \
-            nodeType=$(_maybe_set_true ${NODE_TYPE_LABEL})
-        if [ "$?" != "0" ]; then
-            return 1
+    if [ "${ENABLE_NODE_TYPE_LABELING}" = "true" ]; then
+        # check for nodeType=gpu label used by NVIDIA Fleet Command
+        if [ "${NODE_TYPE_LABEL}" != "" ]; then
+            echo "Restarting GPU clients on NVIDIA Fleet Command"
+            kubectl label --overwrite node ${NODE_NAME} \
+                nodeType=$(_maybe_set_true ${NODE_TYPE_LABEL})
+            if [ "$?" != "0" ]; then
+                return 1
+            fi
         fi
     fi
 
